# Generated by Django 6.0.4 on 2026-04-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_issue_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campus_hub/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Events', 'Events'), ('Nature', 'Nature'), ('Friends', 'Friends'), ('Campus Life', 'Campus Life'), ('Other', 'Other')], default='Campus Life', max_length=50)),
                ('uploader_pseudonym', models.CharField(default='Anonymous Scholar', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_pseudonym', models.CharField(default='Anonymous', max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.campusphoto')),
            ],
        ),
    ]
