# Generated by Django 6.0.4 on 2026-04-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_campusphoto_photocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Faculty reviews stay False until admin approves.'),
        ),
    ]
