# Generated by Django 6.0.4 on 2026-05-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_photolike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feedback.feedback',),
        ),
    ]
