# Generated by Django 6.0.4 on 2026-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_pendingfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusphoto',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
